version: '3.8'

services:

  db:
    image: postgres:latest
    env_file:
      - ".env"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SQL_FILE: ${SQL_FILE}
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JSON_FILE_PATH_STUDENTS: ${JSON_FILE_PATH_STUDENTS}
      JSON_FILE_PATH_ROOMS: ${JSON_FILE_PATH_ROOMS}
    depends_on:
      - db
    env_file:
      - ".env"
    volumes:
      - .:/app
    command: python main.py
    tty: true
    stdin_open: true
