version: '3.8'

services:

  db:
    image: postgres:latest
    env_file:
      - ".env"
    environment:
      POSTGRES_DB: db_students
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      DB_HOST: "127.0.0.1"
      DB_PORT: "5432"
      JSON_FILE_PATH_STUDENTS: "students.json"
      JSON_FILE_PATH_ROOMS: "rooms.json"
      SQL_FILE: "select_queries.sql"
    #   POSTGRES_DB: ${DB_NAME}
    #   POSTGRES_USER: ${DB_USER}
    #   POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - networkName

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ".env"
    volumes:
      - .:/app
    command: python main.py
    tty: true
    stdin_open: true
    networks:
      - networkName

networks:
  networkName:
    name: networkName
