version: '3.8'

services:

  db:
    image: postgres:latest
    env_file:
      - ".env"
    environment:
      POSTGRES_DB: db_students
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      DB_HOST: "db"
      DB_PORT: "5432"
      # JSON_FILE_PATH_STUDENTS: ${JSON_FILE_PATH_STUDENTS}
      # JSON_FILE_PATH_ROOMS: ${JSON_FILE_PATH_ROOMS}
      SQL_FILE: "select_queries.sql"
    #   POSTGRES_DB: ${DB_NAME}
    #   POSTGRES_USER: ${DB_USER}
    #   POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JSON_FILE_PATH_STUDENTS: ${JSON_FILE_PATH_STUDENTS}
      JSON_FILE_PATH_ROOMS: ${JSON_FILE_PATH_ROOMS}
    depends_on:
      - db
    env_file:
      - ".env"
    volumes:
      - .:/app
    command: python main.py
    tty: true
    stdin_open: true
